name: Update Data.gov Datasets

on:
  schedule:
    - cron: "0 0 */3 * *"  # Every 3 days
  workflow_dispatch:

jobs:
  update-datasets:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python scripts/update_data_gov.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data/data_gov_datasets.json
          git commit -m "Update Data.gov cybersecurity datasets (auto)"
          git push
        continue-on-error: true
